### ISSUE TITLE
SQL injection possible

### ISSUE THREAD

**Issue by bschifferer** [kira-95/bpm#5]
Interface allows to enter any username. Username is concatenated with the SQL command without prior checking about the format. It is possible to inject SQL commands via username (and other variables).

Example:
Enter your BPM username: Test' OR 'a'='a
Please copy and paste your validation code from the browser: 

```
$ python3 src/bpm.py Welcome to BPM!
Do you have a BPM account?
0:	Yes
1:	No0
Enter your BPM username: ABC1234' OR 'a'='a         
Please copy and paste your validation code from the browser:
```
Although there is no username ABS1234, the second condition “‘a’ = ‘a” will set the query to True and allows the user to continue the process

**Comment by xiaolim** [comment]
We found that too. The program errors out for now but it's clear that there is no input validation implemented in the code.

Do you have a BPM account?
0:	Yes
1:	No
0
Enter your BPM username: x; DROP TABLE USER;
Traceback (most recent call last):
  File "bpm.py", line 37, in <module>
    main()
  File "bpm.py", line 16, in main
    if auth.welcome():
  File "/Users/limxiaoyu/Downloads/bpm-master/src/auth.py", line 40, in welcome
    user_id = get_username()
  File "/Users/limxiaoyu/Downloads/bpm-master/src/auth.py", line 72, in get_username
    % username).fetchone()
sqlite3.Warning: You can only execute one statement at a time.
