### ISSUE TITLE
No unique credidentials

### ISSUE THREAD

**Issue by bschifferer** [kira-95/bpm#7]
Description: If the user inputs his Spotify access token and this token already exists in the database, the system will crash 

Expected behavior:
If the user inputs his Spotify access token and this token already exists in the database, the system should crash:
Except that multiple users have the same access token (Many BPM accounts to one Spotify account)
Ask the user for another access token (One BPM account to one Spotify account)
Decision has to be made by the Product Owner / Business people, what is the desired behavior

Example:
Credential <token> does exists in the database
```
Welcome to BPM!
Do you have a BPM account?
0:	Yes
1:	No
0
Enter your BPM username: benny
Please copy and paste your validation code from the browser: 
<token>
Traceback (most recent call last):
  File "src/bpm.py", line 37, in <module>
    main()
  File "src/bpm.py", line 16, in main
    if auth.welcome():
  File "/Users/bennys/Projects/Columbia/05_Adv/03 Assignments/03_BugHunt_2/bpm/src/auth.py", line 43, in welcome
    get_code(user_id)
  File "/Users/bennys/Projects/Columbia/05_Adv/03 Assignments/03_BugHunt_2/bpm/src/auth.py", line 132, in get_code
    finish_auth(user_id, auth_code)
  File "/Users/bennys/Projects/Columbia/05_Adv/03 Assignments/03_BugHunt_2/bpm/src/auth.py", line 151, in finish_auth
    VALUES (?, ?, ?, ?);', (user_id, access_token, refresh_token, expires_in))
sqlite3.IntegrityError: UNIQUE constraint failed: Credentials.user_id
```

**Comment by adiza** [comment]
If the access token already exists in the database the system will crash. Additionally, the user is never re-prompt for aninput token of incorrect format or token containing an error. 
```
Welcome to BPM!
Do you have a BPM account?
0:	Yes
1:	No
0
Enter your BPM username: adiza
Please copy and paste your validation code from the browser: 
AQBQDYSWTVpIRqKisuy74tCYyldIy2qaBFptBGhNMprp24dU1Ma1T_WBLKA6hfkavuKFLT_7hJy5FNoNgQ3_HI
Traceback (most recent call last):
  File "bpm.py", line 37, in <module>
    main()
  File "bpm.py", line 16, in main
    if auth.welcome():
  File "/Users/Adiza1/projects/bpm/src/auth.py", line 43, in welcome
    get_code(user_id)
  File "/Users/Adiza1/projects/bpm/src/auth.py", line 132, in get_code
    finish_auth(user_id, auth_code)
  File "/Users/Adiza1/projects/bpm/src/auth.py", line 143, in finish_auth
    resp.raise_for_status()
  File "/Users/Adiza1/anaconda3/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

```
